10 BORDER NOT PI: PAPER NOT PI: CLS: PRINT #NOT PI; INK VAL"2";"Disk version for HC - 07.07.2024 -=george.chirtoaca@gmail.com=-"
20 LOAD *"d";NOT PI;"POTSWORTs"SCREEN$: LOAD *"d";NOT PI;"levelldr"CODE : RANDOMIZE USR VAL "32768": LOAD *"d";NOT PI;"POTSWORTm"CODE
30 PRINT#NOT PI;INK VAL"2";"UNLIMITED LIVES? (y/n)": PAUSE NOT PI: IF INKEY$="y" THEN POKE VAL "46792", VAL "183"
40 RANDOMIZE USR VAL"61504"