   10 BORDER NOT PI: PAPER NOT PI: INK VAL "7": BRIGHT SGN PI: CLS : CLEAR VAL "24464": LOAD "venturamas"SCREEN$ : POKE VAL"23739", CODE "o": LOAD "venturamac"CODE
   20 PRINT#NOT PI;"UNLIMITED LIVES?(y/n)": PAUSE NOT PI: IF INKEY$="y" THEN POKE VAL"50233",VAL"42"
   20 RANDOMIZE USR VAL "24465"